### ISSUE TITLE
Support `anyOf` types

### ISSUE THREAD

**Issue by theoephraim** [openapi-contrib/json-schema-to-openapi-schema#12]
Running into this error
```
Type of string,number,boolean is too confusing for   OpenAPI to understand. Found in {"type":["string","number"  ,"boolean"]}
```

but this should be doable using OpenAPI's [anyOf syntax](https://swagger.io/docs/specification/data-models/data-types/#any)

**Comment by philsturgeon** [comment]
Cool idea. Fancy sending in a PR?

**Comment by theoephraim** [comment]
🔥

**Comment by theoephraim** [comment]
Sorry, this may not be quite the right use of the syntax - investigating. Will comment again when I fix it.
