### ISSUE TITLE
convertSync that does not return a promise

### ISSUE THREAD

**Issue by theoephraim** [openapi-contrib/json-schema-to-openapi-schema#14]
would be useful when not using the  dereference option to be able to call the convert method without await. Super simple to add - will open a PR.

**Comment by philsturgeon** [comment]
PR will be welcome but we're not actively working on this all that much seeing as [OAS3.1 == JSON Schema now](https://apisyouwonthate.com/blog/openapi-v31-and-json-schema-2019-09).
