### ISSUE TITLE
Support newer drafts 07 and 2019-09 (08)

### ISSUE THREAD

**Issue by black-snow** [openapi-contrib/json-schema-to-openapi-schema#15]
Draft 04 is quite dated now. 07 seems to be quite widely spread and `2019-09` (08) is the newest one.

The tool converts my 07 schema conatining an array with `oneOf` fields simply to `fields: { type: 'array', items: [Object] }`.

**Comment by philsturgeon** [comment]
oneOf is valid OpenAPI v3.0 so it should just move that oneOf over. If you'd like to send a PR using your specifics as a test case that'd be appreciated.

**Comment by black-snow** [comment]
I've rewritten my schemas to OAS 3.0 (looking forward to 3.1) so this is not an issue to me anymore. But I'll leave it open and make it a bit more specific.

**Comment by philsturgeon** [comment]
Could you post examples of the input and output so we can look into this, or maybe close it down if its not a problem anymore? Currently this is unactionable,.

**Comment by black-snow** [comment]
I'll close this for now.
