### ISSUE TITLE
Test fails on "Invalid JSON Pointer syntax" when running on Windows

### ISSUE THREAD

**Issue by scscgit** [openapi-contrib/json-schema-to-openapi-schema#18]
When running tests on Windows, step `dereferencing schema with file references` [(in dereference_schema.test.js)](https://github.com/openapi-contrib/json-schema-to-openapi-schema/blob/master/test/dereference_schema.test.js#L86) fails with the following error:

```
  1) dereferencing schema with file references:
     URIError: Invalid JSON Pointer syntax.
      at decodeUriFragmentIdentifier (node_modules\@stoplight\json\index.cjs.js:1:6492)
      at Object.pointerToPath (node_modules\@stoplight\json\index.cjs.js:1:6047)
      at ResolveRunner.<anonymous> (node_modules\@stoplight\json-ref-resolver\runner.js:227:37)
      at Generator.next (<anonymous>)
      at D:\a\json-schema-to-openapi-schema\json-schema-to-openapi-schema\node_modules\tslib\tslib.js:113:75
      at new Promise (<anonymous>)
      at Object.__awaiter (node_modules\tslib\tslib.js:109:16)
      at ResolveRunner.resolve (node_modules\@stoplight\json-ref-resolver\runner.js:216:24)
      at ResolveRunner.<anonymous> (node_modules\@stoplight\json-ref-resolver\runner.js:147:63)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules\tslib\tslib.js:110:62)
```

This can be reproduced by using `windows-latest` instead of `ubuntu-latest` in [test.yml GitHub Action](https://github.com/openapi-contrib/json-schema-to-openapi-schema/blob/master/.github/workflows/test.yml#L7)

**Comment by philsturgeon** [comment]
Would you like to help us out, starting with a pull request to get it running on windows, then see if you can take a swing at fixing anything? At first blush it looks like it's an issue with [json-ref-resolver](https://github.com/stoplightio/json-ref-resolver) which has been deprecated in favour of [json-schema-ref-parser](https://github.com/APIDevTools/json-schema-ref-parser), so if we can switch to that we might be sorted.

**Comment by scscgit** [comment]
Sadly I don't have experience with those specific libraries, do you want me to just send a PR with a broken test after replacing runs-on to `windows-latest`?

* (By the way, the only reason why I discovered this is that I originally had some local issues with setting up the library after being unable to find any npx CLI usage option, and so I tried to also run a test on Windows; but later I accidentally resolved the issues without being able to reproduce the problem anymore, so the test isn't a priority for me, I'm just pointing it out in case it's relevant for you.)

**Comment by jonluca** [comment]
Ha that's too funny, it's because `path.join()` will return platform dependent strings

So `join(__dirname, 'fixtures/definitions.yaml#/definitions/bar');` returns `.../fixtures/...` on linux or mac, but returns `...\fixtures\...` on windows.

This is fixed in https://github.com/openapi-contrib/json-schema-to-openapi-schema/pull/30
