### ISSUE TITLE
Error for compiling by nodenext: Relative import paths

### ISSUE THREAD

**Issue by ghost** [openapi-contrib/json-schema-to-openapi-schema#39]
Hello, I started using your library recently and faced a problem with compiling for nodenext typescript esm modules. This is because of relative import: 
![image](https://user-images.githubusercontent.com/58660439/199510505-0dc190ef-d672-45dd-9d54-791a71c523ea.png)
The solution is go from
![image](https://user-images.githubusercontent.com/58660439/199510715-1a84c554-4473-4965-858c-de1282f07880.png)
to
![image](https://user-images.githubusercontent.com/58660439/199510838-72402f00-86a6-4751-825a-f691cb877dc5.png) Can you fix this on your side? Best regards, Qdea

**Comment by jonluca** [comment]
Should be fixed in https://github.com/openapi-contrib/json-schema-to-openapi-schema/pull/40 sorry for the delay
