### ISSUE TITLE
Outdated dependencies in package.json from NPM

### ISSUE THREAD

**Issue by bcurtin144** [openapi-contrib/json-schema-to-openapi-schema#41]
I just cleared my whole PNPM cache and installed this package. My dependencies reference version 2.2.3:
`"@openapi-contrib/json-schema-to-openapi-schema": "^2.2.3"`

But when I open the package.json file in `node_modules/@openapi-contrib/json-schema-to-openapi-schema` I see the following dependencies:

	"dependencies": {
		"@apidevtools/json-schema-ref-parser": "^9.0.9",
		"json-schema-walker": "^0.0.4",
		"openapi-types": "^12.0.0",
		"yargs": "^17.5.1"
	},
	"devDependencies": {
		"@types/json-schema": "^7.0.11",
		"@typescript-eslint/eslint-plugin": "^5.32.0",
		"@typescript-eslint/parser": "^5.32.0",
		"c8": "^7.12.0",
		"eslint": "^8.21.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-prettier": "^4.2.1",
		"eslint-plugin-unused-imports": "^2.0.0",
		"nock": "^13.2.9",
		"prettier": "^2.7.1",
		"typescript": "^4.7.4",
		"vitest": "^0.21.0"
	},

And the specific problem is that json-schema-walker isn't getting v1, which has the null entry fix: https://github.com/jonluca/json-schema-walker/pull/1

Is something going wrong with the publish to NPM?

**Comment by jonluca** [comment]
Yes, when https://github.com/openapi-contrib/json-schema-to-openapi-schema/pull/40 gets landed it'll autodeploy. Waiting on approval from another maintainer (@philsturgeon)

**Comment by bcurtin144** [comment]
Thank you!

Just learned about the overrides keyword in package.json, as a temporary solution: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by jonluca** [comment]
Great, looks likes it's been merged in. v2.2.4 should have the fix.

**Comment by bcurtin144** [comment]
Awesome. Thanks for such a fast response.

**Comment by philsturgeon** [comment]
Merged #40 which has successfully released v2.2.4.
