### ISSUE TITLE
Version 3 isn't esm friendly anymore

### ISSUE THREAD

**Issue by OlivierCuyp** [openapi-contrib/json-schema-to-openapi-schema#50]
With previous the version 2, I had no issue using this package with tsx or ts-node targeting esm.
Now with version 3, convert is not a function but an object with a default key containing the function.
Here is what I mean:

```sh
Convert2: [AsyncFunction: convert]
Convert3: { default: [AsyncFunction: convert] }
```

Below the steps to reproduce in Node v20.11.1.

**Install**:
```
npm init -y
npm i -D tsx ts-node
npm i json-schema-to-openapi-schema2@npm:@openapi-contrib/json-schema-to-openapi-schema@2 \
          json-schema-to-openapi-schema3@npm:@openapi-contrib/json-schema-to-openapi-schema@3 \
```

**package.json**:
```
{
  // ...
  "type": "module",
  // ...
}
```

**test.ts**:
```ts
import convert2 from 'json-schema-to-openapi-schema2';
import convert3 from 'json-schema-to-openapi-schema3';

console.log('Convert2:', convert2);
console.log('Convert3:', convert3);
```

**tscong.json:**
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true
  }
}
```

**Run with tsx:**
```sh
npx tsx ts-node/esm index.ts
```

**Run with ts-node:**
```sh
node --loader ts-node/esm index.ts
```

**Comment by yehudiduhey** [comment]
Facing the same issue, I don't understand why the transpilation to esm and `commonjs` was replaced by a transpilation that targets `ESM` but that uses module `commonjs`. In my opinion the code should be using `ESM` modules as it's the new standard. And optionally could still have a commonjs transpiled version as it was setup previously.

**Comment by javierlinked** [comment]
I cleaned up shortly project transpilation and  created [this PR](https://github.com/openapi-contrib/json-schema-to-openapi-schema/pull/51) in favour of this.
I had to downgrade in my local project to build [v2.2.6](https://github.com/openapi-contrib/json-schema-to-openapi-schema/releases/tag/v2.2.6) in the meanwhile. 

Not sure who is owning this project actually. @jonluca ?

**Comment by jonluca** [comment]
Thanks for the PR! Merged in

**Comment by daveyarwood** [comment]
Hi all -- I think this might still be an issue? (Either that, or I'm missing something, which is equally possible 😄)

I added `"@openapi-contrib/json-schema-to-openapi-schema": "^3.0.3"` to my ESM project, but I ended up having to do this in order to use the conversion function:

```typescript
import jstoas from '@openapi-contrib/json-schema-to-openapi-schema'

const convert = jstoas.default

await convert(...)
```

**Comment by daveyarwood** [comment]
OK, it turns out that it actually works as expected, _but_ TypeScript seems to think that the function is not callable for some reason:

<img width="1564" alt="Image" src="https://github.com/user-attachments/assets/e58cf283-2cba-4210-a366-4ad3ea8f6be4" />

If I add a `@ts-expect-error` annotation to get it to ignore the issue, it does work and I am able to use the conversion function.

<img width="468" alt="Image" src="https://github.com/user-attachments/assets/740e0fe0-2c5c-4779-8a39-25543a9761dc" />

**Comment by jonluca** [comment]
I added a named export - could try ```import { convert } from '@openapi-contrib/json-schema-to-openapi-schema'``` in v4.0.0?

**Comment by daveyarwood** [comment]
That fixed it -- nice! Thanks for the quick fix! 🙌
