### ISSUE TITLE
Validate if its result is indeed a OAS3 schema

### ISSUE THREAD

**Issue by sebas2day** [openapi-contrib/json-schema-to-openapi-schema#8]
First off: thanks a lot for the effort being put into this.

I have a situation where I had a JSON schema converted to OAS3 schema but it didn't match the oas3 json schema spec. It took me some time to figure out what was causing the issue because I was expecting a oas3 compliant schema. Apparently it were some extra properties that were in the json schema that were directly translated to the oas3 schema but aren't allowed. 

Would it be an idea to always validate whether the transformed result is always oas3 compliant? 
e.g.:
```js
import Ajv from 'ajv';
import draft4 from 'ajv/lib/refs/json-schema-draft-04.json';
import oas3schema from './refs/schema.oas3.json'; 

function validateOAS3Schema(schema) {
  let ajv = new Ajv({
    schemaId: 'id', // draft-04 support requirment.
    allErrors: true,
    jsonPointers: true
  });
  ajv.addMetaSchema(draft4);
  ajv.addSchema(oas3schema);
  let valid = ajv.validate({ $ref: 'https://spec.openapis.org/oas/3.0/schema/2019-04-02#/definitions/Schema' }, schema);
  if (!valid) {
    throw new Error(ajv.errorsText());
  }
}
```

Let me know your ideas :)

**Comment by philsturgeon** [comment]
We might need a "removeOtherProperties" or something. The sister package has a bunch of options like that: https://github.com/openapi-contrib/openapi-schema-to-json-schema#keepnotsupported-array

**Comment by sebas2day** [comment]
That would be an option, or maybe rewrite them as openapi extensions e.g. `x-custom`?

**Comment by philsturgeon** [comment]
Yeah that’ll be good. Think you could take a swing at this? Overwhelmed with OpenAPI related OSS contributions already.

**Comment by sebas2day** [comment]
Great, yeah I can pick this up tomorrow
