### ISSUE TITLE
Does this work with json schema draft 4?

### ISSUE THREAD

**Issue by milliechan** [openapi-contrib/json-schema-to-openapi-schema#9]
Hi there, I tried running the example code but imported my json schema draft 4 schema and noticed that it output invalid openapiv3.

There were missing properties like `openapi` and `info`. Additionally the `links` property from json schema didn't transform into `paths`. Is that expected? Thanks!

**Comment by philsturgeon** [comment]
Hey @milliechan. This tool will not create entire OpenAPI documents, it converts a JSON Schema files to to an [OpenAPI Schema Object](http://spec.openapis.org/oas/v3.0.3#schema-object). 

Maybe swing by slack.apisyouwonthate.com and I can help with your use case. I have spent far too much time on OAS <!=> JSON Schema so will be able to help one way or another.
